config/routes.rb
Rails.application.routes.draw do
  resources :queries, only: [:index]
  resources :sessions, only: [:new, :create, :destroy, :reset]
  root to: "sessions#new"
  get "/reset", to: "sessions#reset"
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index 
    payload = query_params
    if payload[:query_action].present?
      begin
      query_type = Queries.detect {|q| q[:action] == payload[:query_action].to_sym }
      payload[query_type[:input][:name]] = payload[:sql_string]
      
      @results = eval(query_type[:query])
      if @results.is_a? ActiveRecord::ActiveRecordError
        @error = @results
        @results = Nil
      else
        @results.inspect if @results.is_a? ActiveRecord::Relation
      end
      rescue Exception => e
            @error = e
            @results = nil
      end
    end
    if query_type
      @sql_string = query_type[:sql].gsub("'REPLACE'", payload[:sql_string])
      @previous_params = payload
    end
    @queries = Queries
    @query_collection ||= Queries.collect{|q| [q[:name], q[:action]] }
  end

  private

  def query_params
    params.permit(:query_action, :sql_string, :commit)
  end
end

app/views/queries/_results.html.erb
<%= turbo_frame_tag "query_builder" do %>
  <div>
    <% if @results %>
      <h2>Results</h1>
      <%= @result.inspect %>
    <% end %>

    <% if @previous_params %>
      <h2>Params were:</h2>
      <%= @previous_params.inspect %>
    <% end %>

    <% if @error %>
      <h2>Error Message:</h2>
      <%= @error.inspect %>

    <% end %>
  </div>
<% end %>

app/views/queries/_sql_form.html.erb
  <%= form_with url: queries_path(turbo_frame: "query_builder"), method: :get, html: {name:'query-form'} do |f| %>
    <div class="form-group mr-1" %>
      <%= label_tag "What Active Record method would you like to work with?" %></br>
      <%= f.select "query_action", @query_collection, {selected: params[:query_action]}, {class: "custom-select custom-select-lg", onchange: "showContent(event)", required: true
      } %>
    </div>

    <%= label_tag "Add form input which will be injected into your Active Record Method:" %></br>
    <div class="form-group" %>
      <%= f.text_field 'sql_string', value: params[:sql_string], id: "textarea", size: 50, required: true %>
    </div>

    <div class="form-group" %>
      <button type="button" id='clearForm', class="btn btn-primary" onclick="jqResetForm('query-form')">Clear</button>
      <%= f.submit("Submit SQL Query", string: nil, class: "btn btn-primary") %>
    </div>
  <% end %>

<turbo-frame id="query_builder" target="_top"></turbo-frame>

app/views/queries/index.html+turbo_frame.erb
<%= turbo_frame_tag "query_builder" do %>
  <div>
    <% if @results %>
      <h2>Results</h1>
      <%= @result.inspect %>

    <% elsif @previous_params %>
      <h2>Params were:</h2>
      <%= @previous_params.inspect %>

    <% elsif @error %>
      <h2>Error Message:</h2>
      <%= @error.inspect %>

    <% end %>
  </div>
<% end %>

app/views/queries/index.html.erb
<div class="row">
  <div class="col-5">
    <h1 class="fst-italic">Inject Some SQL!</h1>
    <%= render 'sql_form' %>
  
  <%= turbo_frame_tag "query_builder" do %>

  <div class="row feedback">
    <div class="col-12">
      <div class="pt-2">
        <% if @error %>
          <h4>Error Message:</h4>
          <%= @error.inspect %>
        <% end %>
      </div>
      <div class="pt-2">
        <% if @results %>
          <h4>Return Value</h4>
          <%= ruby_color @results.inspect %>
        <% end %>
      </div>
      <div class="pt-2">
        <% if @sql_string %>
          <h4>Actual SQL</h4>
          <%= sql_color @sql_string %>
      </div>
      <% end %>
    </div>  
  </div>  
<% end %>
</div>

  <div class = "col-7">
    <div id='Choose a method' class='card selected_content default'>
      Choose an Active Record method to learn more about how to exploit it.
    </div>
    <div>
      <% @queries.each do |q| %>
        <div class='card selected_content' id='<%= q[:action] %>'>
          <div class="card-header">
            <a href="<%= q[:link] %>" target="_blank"><%= q[:name] %></a>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <h6 class="subtitle">Active Record:</h6>
              <%= ruby_color q[:query] %>
            </li>
            <li class="list-group-item">
              <h6 class="subtitle">Generated SQL:</h6>
              <%= sql_color q[:sql] %>
            </li>
            <li class="list-group-item">
              <%= q[:explanation] %>
            </li>
            <li class="list-group-item">
              <h6 class="subtitle">Spoiler:
              <blockquote class="spoiler">
                <%= q[:input][:example] %>
              </blockquote>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>